const recipesData = [
    {
        id: 1,
        name: 'Spaghetti Carbonara',
        cuisine: 'Italian',
        making: 'Baking',
        time: 30,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://thesecretsuppersociety.com/wp-content/uploads/2022/03/spagetti-carbonara.jpg',
        link: 'https://www.youtube.com/results?search_query=Spaghetti+Carbonara+live'
    },
    {
        id: 2,
        name: 'Chicken Tikka Masala',
        cuisine: 'Indian',
        making: 'Grilling',
        time: 45,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://www.shutterstock.com/image-photo/chicken-tikka-masala-served-bowl-600nw-2502136341.jpg',
        link: 'https://www.youtube.com/results?search_query=Chicken+Tikka+Masala+live'
    },
    {
        id: 3,
        name: 'Sushi Rolls',
        cuisine: 'Japanese',
        making: 'Steaming',
        time: 60,
        difficulty: 'Hard',
        nutrition: 'Gluten-Free',
        mealType: 'Lunch',
        seasonal: 'Spring',
        image: 'https://cdn.pickuplimes.com/cache/a6/7d/a67d95e8044769cf96d551c0ad09f7f9.jpg',
        link: 'https://www.youtube.com/results?search_query=Sushi+Rolls+live'
    },
    {
        id: 4,
        name: 'Tacos',
        cuisine: 'Mexican',
        making: 'Frying',
        time: 20,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Snack',
        seasonal: 'Summer',
        image: 'https://carveyourcraving.com/wp-content/uploads/2020/09/Easy-vegetarian-tacos.jpg',
        link: 'https://www.youtube.com/results?search_query=Tacos+live'
    },
    {
        id: 5,
        name: 'Beef Stroganoff',
        cuisine: 'Russian',
        making: 'Sautéing',
        time: 40,
        difficulty: 'Medium',
        nutrition: 'High-Calorie',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://supermancooks.com/wp-content/uploads/2023/03/beef-stroganoff-featured.jpg',
        link: 'https://www.youtube.com/results?search_query=Beef+Stroganoff+live'
    },
    {
        id: 6,
        name: 'Vegetable Stir Fry',
        cuisine: 'Chinese',
        making: 'Stir-frying',
        time: 25,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Lunch',
        seasonal: 'Spring',
        image: 'https://images.themodernproper.com/billowy-turkey/production/posts/VegetableStirFry_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1703377301&s=3484d660c4b404c6d23b0c3ec7ac66eb',
        link: 'https://www.youtube.com/results?search_query=Vegetable+Stir+Fry+live'
    },
    {
        id: 7,
        name: 'Pancakes',
        cuisine: 'American',
        making: 'Baking',
        time: 20,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Breakfast',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSltnWpxyPOe9rfl5tYb0VycB-rUjWcn4mwxkjZGzDJndmH_huCsCbzisHw7udSsa7RZXs&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Pancakes+live'
    },
    {
        id: 8,
        name: 'Margarita Pizza',
        cuisine: 'Italian',
        making: 'Baking',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'Vegetarian',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://www.cookingclassy.com/wp-content/uploads/2017/08/margherita-pizza-9.jpg',
        link: 'https://www.youtube.com/results?search_query=Margarita+Pizza+live'
    },
    {
        id: 9,
        name: 'Ceviche',
        cuisine: 'Peruvian',
        making: 'Marinating',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Spring',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4VcijftbKSaCeFHDjEtmd83nJu6jxGcRZT_Uk3P6ekpyYI-iWpI-H17x9OP40ktZQwLo&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Ceviche+live'
    },
    {
        id: 10,
        name: 'Pasta Primavera',
        cuisine: 'Italian',
        making: 'Boiling',
        time: 35,
        difficulty: 'Medium',
        nutrition: 'Vegetarian',
        mealType: 'Lunch',
        seasonal: 'Summer',
        image: 'https://reciperunner.com/wp-content/uploads/2016/04/pasta-primavera-4.jpg',
        link: 'https://www.youtube.com/results?search_query=Pasta+Primavera+live'
    },
    {
        id: 11,
        name: 'Chocolate Cake',
        cuisine: 'French',
        making: 'Baking',
        time: 60,
        difficulty: 'Hard',
        nutrition: 'High-Calorie',
        mealType: 'Dessert',
        seasonal: 'Any',
        image: 'https://images.app.goo.gl/KuWag814MpU6JGUX6',
        link: 'https://www.youtube.com/results?search_query=Chocolate+Cake+live'
    },
    {
        id: 12,
        name: 'Chili Con Carne',
        cuisine: 'Mexican',
        making: 'Simmering',
        time: 50,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9e3jvfcBxEpS8FT02v8nUz3snlOrP-zOPVXkuf6WniC4SKs7fzIahmuw84uLI39qGAIQ&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Chili+Con+Carne+live'
    },
    {
        id: 13,
        name: 'Caesar Salad',
        cuisine: 'Italian',
        making: 'Mixing',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Summer',
        image: 'https://cookieandkate.com/images/2021/05/caesar-salad-in-bowl.jpg',
        link: 'https://www.youtube.com/results?search_query=Caesar+Salad+live'
    },
    {
        id: 14,
        name: 'Pad Thai',
        cuisine: 'Thai',
        making: 'Stir-frying',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3bgJN_Ny1LPy1GwviD3IrD5Hg-eCEVp0TzOWt7HttnkPh5Cq2PE_ixxscyol2wHtkgIg&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Pad+Thai+live'
    },
    {
        id: 15,
        name: 'Ratatouille',
        cuisine: 'French',
        making: 'Baking',
        time: 40,
        difficulty: 'Medium',
        nutrition: 'Vegan',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://images.immediate.co.uk/production/volatile/sites/30/2019/05/Ratatouille-ea27a5c.jpg',
        link: 'https://www.youtube.com/results?search_query=Ratatouille+live'
    },
    {
        id: 16,
        name: 'Croissants',
        cuisine: 'French',
        making: 'Baking',
        time: 180,
        difficulty: 'Hard',
        nutrition: 'High-Calorie',
        mealType: 'Breakfast',
        seasonal: 'Any',
        image: 'https://veenaazmanov.com/wp-content/uploads/2020/05/Homemade-Croissants-Recipe60.jpg',
        link: 'https://www.youtube.com/results?search_query=Croissants+live'
    },
    {
        id: 17,
        name: 'Fried Rice',
        cuisine: 'Chinese',
        making: 'Stir-frying',
        time: 20,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Lunch',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOkGCErt3GApm5_IP64RpDm_rSWx_fiBDTBhYTNk8gr6N1LggFuiv0Y65dy61mR_s4eBA&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Fried+Rice+live'
    },
    {
        id: 18,
        name: 'Beef Tacos',
        cuisine: 'Mexican',
        making: 'Frying',
        time: 25,
        difficulty: 'Easy',
        nutrition: 'High-Protein',
        mealType: 'Snack',
        seasonal: 'Summer',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4SMpuC2m1nLTKNfnl98oNaPDVmRgIcf2OYgk15iDYgDg5wv4d_-KN7TR4e5f1f9ejU_8&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Beef+Tacos+live'
    },
    {
        id: 19,
        name: 'Pasta Carbonara',
        cuisine: 'Italian',
        making: 'Boiling',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Calorie',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://www.thereciperebel.com/wp-content/uploads/2023/12/spaghetti-carbonara-TRR-12-of-28.jpg',
        link: 'https://www.youtube.com/results?search_query=Pasta+Carbonara+live'
    },
    {
        id: 20,
        name: 'Gyoza',
        cuisine: 'Japanese',
        making: 'Steaming',
        time: 45,
        difficulty: 'Hard',
        nutrition: 'Gluten-Free',
        mealType: 'Snack',
        seasonal: 'Winter',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs3i8RhiC-C-AygnlZ2We25rzD_Uh4NIqAPsJ339tCjyHmY0OQ5TI2Pi-UtqEp52JIWn0&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Gyoza+live'
    },
    {
        id: 21,
        name: 'Pumpkin Soup',
        cuisine: 'American',
        making: 'Blending',
        time: 30,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Appetizer',
        seasonal: 'Fall',
        image: 'https://www.twopeasandtheirpod.com/wp-content/uploads/2020/10/pumpkin-soup-4.jpg',
        link: 'https://www.youtube.com/results?search_query=Pumpkin+Soup+live'
    },
    {
        id: 22,
        name: 'Eggplant Parmesan',
        cuisine: 'Italian',
        making: 'Baking',
        time: 50,
        difficulty: 'Medium',
        nutrition: 'Vegetarian',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnuJYQG-JYTgFBw_6DPauNLM45rHYVcJoNuD0ukhH65RoVXnYdn7Sbxi2FFbqVDN3J64&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Eggplant+Parmesan+live'
    },
    {
        id: 23,
        name: 'Biryani',
        cuisine: 'Indian',
        making: 'Cooking',
        time: 60,
        difficulty: 'Hard',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://glebekitchen.com/wp-content/uploads/2019/12/chickenbiryanibowltop.jpg',
        link: 'https://www.youtube.com/results?search_query=Biryani+live'
    },
    {
        id: 24,
        name: 'Pesto Pasta',
        cuisine: 'Italian',
        making: 'Boiling',
        time: 30,
        difficulty: 'Easy',
        nutrition: 'Vegetarian',
        mealType: 'Lunch',
        seasonal: 'Spring',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXIhMleL0iXU6r0Vn-zoV-gN_nYpJR_22ly2Y3WPdDNDigzBMzX_jRcWiUbHUBXIWMdjg&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Pesto+Pasta+live'
    },
    {
        id: 25,
        name: 'Baklava',
        cuisine: 'Turkish',
        making: 'Baking',
        time: 90,
        difficulty: 'Hard',
        nutrition: 'High-Calorie',
        mealType: 'Dessert',
        seasonal: 'Any',
        image: 'https://visitturkey.in/wp-content/uploads/2024/07/turkish-baklava.webp',
        link: 'https://www.youtube.com/results?search_query=Baklava+live'
    },
    {
        id: 26,
        name: 'Quiche Lorraine',
        cuisine: 'French',
        making: 'Baking',
        time: 60,
        difficulty: 'Medium',
        nutrition: 'High-Calorie',
        mealType: 'Brunch',
        seasonal: 'Any',
        image: 'https://www.eatingwell.com/thmb/WQJJameVA8qPRJ-ai6v2w7MKHME=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/7787187-c1ba3239e9e1421982fcc2092a87b772.jpg',
        link: 'https://www.youtube.com/results?search_query=Quiche+Lorraine+live'
    },
    {
        id: 27,
        name: 'Fettuccine Alfredo',
        cuisine: 'Italian',
        making: 'Boiling',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Calorie',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://images.app.goo.gl/i47v7cGpuUdLDPKU6',
        link: 'https://www.youtube.com/results?search_query=Fettuccine+Alfredo+live'
    },
    {
        id: 28,
        name: 'Lentil Soup',
        cuisine: 'Middle Eastern',
        making: 'Simmering',
        time: 45,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Lunch',
        seasonal: 'Any',
        image: 'https://www.aheadofthyme.com/wp-content/uploads/2021/09/fettuccine-alfredo.jpg',
        link: 'https://www.youtube.com/results?search_query=Lentil+Soup+live'
    },
    {
        id: 29,
        name: 'Chicken Noodle Soup',
        cuisine: 'American',
        making: 'Simmering',
        time: 40,
        difficulty: 'Easy',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTttweu6R_PBz9wIkgLhYnKx-xJ3FGiYONdXZGA7J4NSEhPc53wGZCG-ox5N7ZD_l7tPvY&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Chicken+Noodle+Soup+live'
    },
    {
        id: 30,
        name: 'Seafood Paella',
        cuisine: 'Spanish',
        making: 'Cooking',
        time: 50,
        difficulty: 'Hard',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://www.dinneratthezoo.com/wp-content/uploads/2020/10/seafood-paella-4.jpg',
        link: 'https://www.youtube.com/results?search_query=Seafood+Paella+live'
    },
    {
        id: 31,
        name: 'Coconut Curry',
        cuisine: 'Thai',
        making: 'Simmering',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'Vegan',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz11rLdyY8sJdZJJNSJcPiK5KfH-GVCpx69R1b5Cj5Z0ut6CqEY0aMx0wOaUdGGarN5pU&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Coconut+Curry+live'
    },
    {
        id: 32,
        name: 'Cheeseburger',
        cuisine: 'American',
        making: 'Grilling',
        time: 25,
        difficulty: 'Easy',
        nutrition: 'High-Calorie',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://www.recipetineats.com/tachyon/2022/08/Stack-of-cheeseburgers.jpg',
        link: 'https://www.youtube.com/results?search_query=Cheeseburger+live'
    },
    {
        id: 33,
        name: 'Greek Salad',
        cuisine: 'Greek',
        making: 'Mixing',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Summer',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu2sw-Jj-rS8s6SktP9hEcZSHjh1hRfIsSVTzh3QAxy14p0jxaLwFD2XsG9GiSznTq8Q8&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Greek+Salad+live'
    },
    {
        id: 34,
        name: 'Stuffed Peppers',
        cuisine: 'Mexican',
        making: 'Baking',
        time: 45,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://cdn.loveandlemons.com/wp-content/uploads/2020/08/stuffed-peppers.jpg',
        link: 'https://www.youtube.com/results?search_query=Stuffed+Peppers+live'
    },
    {
        id: 35,
        name: 'Minestrone Soup',
        cuisine: 'Italian',
        making: 'Simmering',
        time: 40,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Lunch',
        seasonal: 'Winter',
        image: 'https://cookieandkate.com/images/2018/01/vegetarian-minestrone-soup-recipe.jpg',
        link: 'https://www.youtube.com/results?search_query=Minestrone+Soup+live'
    },
    {
        id: 36,
        name: 'Beef Enchiladas',
        cuisine: 'Mexican',
        making: 'Baking',
        time: 60,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://www.dinneratthezoo.com/wp-content/uploads/2019/09/beef-enchiladas-5.jpg',
        link: 'https://www.youtube.com/results?search_query=Beef+Enchiladas+live'
    },
    {
        id: 37,
        name: 'Banana Bread',
        cuisine: 'American',
        making: 'Baking',
        time: 60,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Breakfast',
        seasonal: 'Any',
        image: 'https://www.allrecipes.com/thmb/POFbIVTzNctFvvh1JIlMSRHAeZE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20144-banana-banana-bread-mfs-60-bddcb8e0caac452386de52f6fecf33db.jpg',
        link: 'https://www.youtube.com/results?search_query=Banana+Bread+live'
    },
    {
        id: 38,
        name: 'Roasted Vegetables',
        cuisine: 'Mediterranean',
        making: 'Roasting',
        time: 40,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://www.wellplated.com/wp-content/uploads/2021/12/What-to-do-with-roasted-vegetables.jpg',
        link: 'https://www.youtube.com/results?search_query=Roasted+Vegetables+live'
    },
    {
        id: 39,
        name: 'Tom Yum Soup',
        cuisine: 'Thai',
        making: 'Simmering',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'Gluten-Free',
        mealType: 'Lunch',
        seasonal: 'Winter',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_kXZzJlNnvx3PrNC0Rw7n-8X2YzvZBhViGj-5mq5FVW4yiX3FH5lM6FYz8MFDYnI_RPU&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Tom+Yum+Soup+live'
    },
    {
        id: 40,
        name: 'Chocolate Chip Cookies',
        cuisine: 'American',
        making: 'Baking',
        time: 25,
        difficulty: 'Easy',
        nutrition: 'High-Calorie',
        mealType: 'Dessert',
        seasonal: 'Any',
        image: 'https://handletheheat.com/wp-content/uploads/2020/10/BAKERY-STYLE-CHOCOLATE-CHIP-COOKIES-9-637x637-1.jpg',
        link: 'https://www.youtube.com/results?search_query=Chocolate+Chip+Cookies+live'
    },
    {
        id: 41,
        name: 'Chicken Fajitas',
        cuisine: 'Mexican',
        making: 'Grilling',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf_2XTK2citicCPTzZx_bgCo2kgJs2zp8HQ1mVaCAGhibqrpP4pPMSQNuJzsBAMfKP-Dw&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Chicken+Fajitas+live'
    },
    {
        id: 42,
        name: 'Potato Salad',
        cuisine: 'American',
        making: 'Mixing',
        time: 20,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Summer',
        image: 'https://hips.hearstapps.com/hmg-prod/images/classic-potato-salad-index-6425b6f9bd7d2.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=1200:*',
        link: 'https://www.youtube.com/results?search_query=Potato+Salad+live'
    },
    {
        id: 43,
        name: 'Ramen',
        cuisine: 'Japanese',
        making: 'Simmering',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbWf8FJDpTBUFYSledCqfpz8uPCEhTDmqxaJXXm3PShCMIVVIsgQQwwV9ycpE5bvwfvbY&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Ramen+live'
    },
    {
        id: 44,
        name: 'Fruit Smoothie',
        cuisine: 'American',
        making: 'Blending',
        time: 10,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Breakfast',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwybxXB4B_eHPxHnfPs7R8h1zcmWaUVtsDAxgOqU1nHwlIgkX7wx4fDlcvKM8tHMrf86M&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Fruit+Smoothie+live'
    },
    {
        id: 45,
        name: 'Shepherds Pie',
        cuisine: 'British',
        making: 'Baking',
        time: 60,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Winter',
        image: 'https://www.recipetineats.com/uploads/2018/06/Shepherds-Pie_1.jpg',
        link: 'https://www.youtube.com/results?search_query=Shepherd’s+Pie+live'
    },
    {
        id: 46,
        name: 'Chili Con Carne',
        cuisine: 'Mexican',
        making: 'Simmering',
        time: 90,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://www.lurch.de/media/19/ce/a4/1694766618/Schnelles%20Chili%20con%20Carne.jpg',
        link: 'https://www.youtube.com/results?search_query=Chili+Con+Carne+live'
    },
    {
        id: 47,
        name: 'Caprese Salad',
        cuisine: 'Italian',
        making: 'Mixing',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Summer',
        image: 'https://www.recipetineats.com/tachyon/2019/01/Caprese-Salad_8.jpg',
        link: 'https://www.youtube.com/results?search_query=Caprese+Salad+live'
    },
    {
        id: 48,
        name: 'Pancakes',
        cuisine: 'American',
        making: 'Grilling',
        time: 20,
        difficulty: 'Easy',
        nutrition: 'High-Calorie',
        mealType: 'Breakfast',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_vEOto8yFYInLNZleAL0ywLnolVBf5_FoWoWKhzgvBXNzv9sJVk-lIVlhN37EOiGpfSw&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Pancakes+live'
    },
    {
        id: 49,
        name: 'Beef Stroganoff',
        cuisine: 'Russian',
        making: 'Simmering',
        time: 50,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://www.paleorunningmomma.com/wp-content/uploads/2020/12/beef-stroganoff-9.jpg',
        link: 'https://www.youtube.com/results?search_query=Beef+Stroganoff'
    },
    {
        id: 50,
        name: 'Vegetable Stir Fry',
        cuisine: 'Asian',
        making: 'Stir-Frying',
        time: 25,
        difficulty: 'Easy',
        nutrition: 'Vegan',
        mealType: 'Lunch',
        seasonal: 'Any',
        image: 'https://therecipecritic.com/wp-content/uploads/2019/08/vegetable_stir_fry.jpg',
        link: 'https://www.youtube.com/results?search_query=Vegetable+Stir+Fry'
    },
    {
        id: 51,
        name: 'Pork Chops',
        cuisine: 'American',
        making: 'Grilling',
        time: 35,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST5kLrtffNqT2U_Jq0sxG-yhZ4pJkCtwPobioarQMojEDjFUi7izkaFKAMjddOLk55ASw&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Pork+Chops'
    },
    {
        id: 52,
        name: 'Sushi',
        cuisine: 'Japanese',
        making: 'Rolling',
        time: 60,
        difficulty: 'Hard',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://properfoodie.com/wp-content/uploads/2020/07/featured-sushi-2b-feature-sushi-2b-1.jpg',
        link: 'https://www.youtube.com/results?search_query=Sushi'
    },
    {
        id: 53,
        name: 'Taco Salad',
        cuisine: 'Mexican',
        making: 'Mixing',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Any',
        image: 'https://peasandcrayons.com/wp-content/uploads/2021/01/vegetarian-taco-salad-recipe-3.jpg',
        link: 'https://www.youtube.com/results?search_query=Taco+Salad'
    },
    {
        id: 54,
        name: 'Chocolate Mousse',
        cuisine: 'French',
        making: 'Chilling',
        time: 180,
        difficulty: 'Hard',
        nutrition: 'High-Calorie',
        mealType: 'Dessert',
        seasonal: 'Any',
        image: 'https://carlsbadcravings.com/wp-content/uploads/2020/12/Chocolate-Mousse-Cake-21-500x500.jpg',
        link: 'https://www.youtube.com/results?search_query=Chocolate+Mousse'
    },
    {
        id: 55,
        name: 'Stuffed Zucchini',
        cuisine: 'Mediterranean',
        making: 'Baking',
        time: 50,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoqAov3VcuQ4KQqkhXIFUOPFX3Mj2NHUtqgPdMJ5lMUQUNXZ68AceqyasJu2uRdRGoUzg&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Stuffed+Zucchini'
    },
    {
        id: 56,
        name: 'Eggplant Parmesan',
        cuisine: 'Italian',
        making: 'Baking',
        time: 60,
        difficulty: 'Medium',
        nutrition: 'High-Calorie',
        mealType: 'Dinner',
        seasonal: 'Fall',
        image: 'https://www.eatingwell.com/thmb/8igrklp0Wlt9nkeNGawc9vBC9Uc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grilled-eggplant-parmesan-2000-ce486c66cbfe43c6bdcb23f3b799191b.jpg',
        link: 'https://www.youtube.com/results?search_query=Eggplant+Parmesan'
    },
    {
        id: 57,
        name: 'Beef Tacos',
        cuisine: 'Mexican',
        making: 'Grilling',
        time: 30,
        difficulty: 'Medium',
        nutrition: 'High-Protein',
        mealType: 'Dinner',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2XWB64ntWHjiTHJnQoTD6rJ6E0ja0bwoUWzhPuWMS5dvLg-b72FERvze24sHHFVVMrwI&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Beef+Tacos'
    },
    {
        id: 58,
        name: 'Vanilla Pudding',
        cuisine: 'American',
        making: 'Chilling',
        time: 120,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Dessert',
        seasonal: 'Any',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkoWgNAiiuFcPsdH3gmsihAI0TbWERQ4WriFEPhdX443bjwhDfk7l8sizc2sjf5YnTq-c&usqp=CAU',
        link: 'https://www.youtube.com/results?search_query=Vanilla+Pudding'
    },
    {
        id: 59,
        name: 'Ratatouille',
        cuisine: 'French',
        making: 'Baking',
        time: 90,
        difficulty: 'Medium',
        nutrition: 'Vegan',
        mealType: 'Dinner',
        seasonal: 'Summer',
        image: 'https://images.squarespace-cdn.com/content/v1/58d1f7308419c23d328cdb22/c45f540a-8889-441a-8b4c-c6a359534b62/Ratatouille',
        link: 'https://www.youtube.com/results?search_query=Ratatouille'
    },
    {
        id: 60,
        name: 'Caesar Salad',
        cuisine: 'Italian',
        making: 'Mixing',
        time: 15,
        difficulty: 'Easy',
        nutrition: 'Low-Calorie',
        mealType: 'Lunch',
        seasonal: 'Any',
        image: 'https://cookieandkate.com/images/2021/05/caesar-salad-in-bowl.jpg',
        link: 'https://www.youtube.com/results?search_query=Caesar+Salad'
    },
];

export default recipesData;